services:

    # Forms
    stems.media.form.type.image:
        class: Stems\MediaBundle\Form\ImageType
        arguments: 
            categories: %stems.media.image.categories%
        tags:
            - { name: form.type, alias: media_image_type }

    # Services
    stems.media.twig.media_extension:
            class: Stems\MediaBundle\Twig\MediaExtension
            arguments: 
                em: "@doctrine.orm.entity_manager"
            tags:
                - { name: twig.extension }