parameters:
#    stems_media.example.class: Stems\MediaBundle\Example

services:
#    stems_media.example:
#        class: %stems_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
