services:
    stems.media.twig.media_extension:
            class: Stems\MediaBundle\Twig\MediaExtension
            arguments: 
                em: "@doctrine.orm.entity_manager"
            tags:
                - { name: twig.extension }